routes/web.php
            Route::post('suspend-resident', 'Admin\ResidentController@suspendResident')->name('suspend-resident');

            Route::post('house-by-address', 'Admin\ResidentController@houseByAddress')->name('house-by-address');

            Route::get('/test1', 'Admin\ResidentController@test1');
            Route::post('/save-token', 'Admin\ResidentController@saveToken')->name('save-token');
            Route::post('/send-notification', 'Admin\ResidentController@sendNotification')->name('send.notification');

            Route::get('/test2', 'Admin\ResidentController@test2');

            // Approve List
            Route::resource('approve-list', 'Admin\ApproveListController');
            Route::get('approve-list-byid/{id}', 'Admin\ApproveListController@createdbyResedentID')->name('approve-list-byid');
            Route::get('approved-data/{id}', 'Admin\ApproveListController@residentData')->name('approved-data');
            Route::post('delete-approved/{contract_id}/{resident_id}', 'Admin\ApproveListController@destroy')->name('delete-approve-by-guard');


        });

    });

//    });

    //setting prefix
    Route::group(['prefix' => 'settings', 'as' => 'settings.'], function () {

        //dashboard setting routes
        Route::resource('dashboard-setting', 'Admin\DashboardSettingController')->middleware('checkGuardAdmin');

        Route::group(['middleware' => 'checkKiosk'], function () {

            Route::get('dashboard-setting-data', 'Admin\DashboardSettingController@dashboardData')->name('dashboard-setting-data');
            Route::post('dashboard-setting-web-relay', 'Admin\DashboardSettingController@enableWebRelay')->name('dashboard-setting-web-relay');

            //email templates routes
            Route::resource('email-templates', 'Admin\EmailTemplateController')->middleware(['checkCommunityAdmin', 'checkGuardAdmin']);
            Route::get('email-templates-data', 'Admin\EmailTemplateController@emailTemplateData')->name('email-templates-data');

            Route::get('guest-arrival-email', 'Admin\EmailTemplateController@guestArrivalEmail');

            //printer templates routes
            Route::resource('printer-templates', 'Admin\PrinterTemplateController');
            Route::get('printer-templates-data', 'Admin\PrinterTemplateController@printerTemplateData')->name('printer-templates-data');
            Route::post('delete-printer-template/{userId}', 'Admin\PrinterTemplateController@deletePrinterTemplate')->name('delete-printer-template');


        });

        //scanners routes
        Route::resource('scanners', 'Admin\ScannerController')->middleware('checkGuardAdmin');

        //guest logs routes
        Route::get('scan-logs', 'Admin\GuestLogController@index');


        Route::get('scanners-data', 'Admin\ScannerController@scannerData')->name('scanners-data');

        Route::post('get-cameras-by-community', 'Admin\CameraController@getCamerasByCommunity')->name('get-cameras-by-community');


        //auth logs routes
        Route::get('auth-logs', 'Admin\AuthLogController@index')->name('auth-logs')->middleware('checkCommunityAdmin', 'checkGuardAdmin');

        Route::get('auth-logs-data', 'Admin\AuthLogController@authLogData')->name('auth-logs-data');
        Route::group(['middleware' => 'checkKiosk'], function () {

            //offensive words routes
            Route::resource('offensive-words', 'Admin\OffensiveWordController')->middleware('checkGuardAdmin');
            Route::get('offensive-words-data', 'Admin\OffensiveWordController@offensiveWordsData')->name('offensive-words-data');


        });
        //camera routes
        Route::resource('cameras', 'Admin\CameraController')->middleware('checkGuardAdmin');
        Route::get('cameras-data', 'Admin\CameraController@cameraData')->name('cameras-data');
        Route::resource('web-relay-tracking', 'Admin\WebRelayTrackingController');
        Route::get('web-relay-tracking-data', 'Admin\WebRelayTrackingController@webRelayTrackingData')->name('web-relay-tracking-data');


        Route::group(['middleware' => 'checkKiosk'], function () {

            Route::resource('web-relays', 'Admin\WebRelayController');
            Route::get('web-relays-data', 'Admin\WebRelayController@webRelayData')->name('web-relays-data');

            //Mark:- Remote Web Relay Trackings
            Route::resource('remote-web-relay-tracking', 'Admin\RemoteWebRelayTrackingController');
            Route::get('remote-web-relay-tracking-data', 'Admin\RemoteWebRelayTrackingController@webRelayTrackingData')->name('remote-web-relay-tracking-data');

        });
    });


    Route::get('guest-logs-data', 'Admin\GuestLogController@guestLogData')->name('guest-logs-data');

    //request passes routes
    Route::get('pass-requests', 'Admin\PassRequestController@index')->name('pass-requests');
    Route::get('pass-requests-data', 'Admin\PassRequestController@passRequestData')->name('pass-requests-data');

    Route::group(['middleware' => 'checkKiosk'], function () {

        //traffic tickets prefix
        Route::group(['middleware' => 'checkGuardAdmin', 'prefix' => 'traffic-tickets', 'as' => 'traffic-tickets.'], function () {

            //community tickets
            Route::resource('tickets-logix-communities', 'Admin\CommunityTicketController');
            Route::get('tickets-logix-communities-data', 'Admin\CommunityTicketController@communityTicketData')->name('tickets-logix-communities-data');
            Route::get('fetch-tickets-by-community/{id}', 'Admin\CommunityTicketController@fetchCommunityTicketData')->name('fetch-tickets-by-community');

            //dashboard setting routes
            Route::resource('resident-tickets', 'Admin\ResidentTicketController')->middleware('checkGuardAdmin');
            Route::get('resident-ticket-data', 'Admin\ResidentTicketController@residentTicketData')->name('resident-tickets-data');
            Route::post('resident-ticket-data', 'Admin\ResidentTicketController@residentTicketData');
            Route::get('resident-ticket-details', 'Admin\ResidentTicketController@ticketDetails')->name('resident-ticket-details');
            Route::get('resident-ticket-Images', 'Admin\ResidentTicketController@ticketImages')->name('resident-ticket-images');
            Route::get('resident-email-templates', 'Admin\ResidentTicketController@getTicketTemplatesByCommunity')->name('resident-email-templates');
            Route::post('resident-email-send', 'Admin\ResidentTicketController@sendEmail')->name('resident-email-send');
            Route::post('resident-payment', 'Admin\ResidentTicketController@payment')->name('resident-payment');
            Route::patch('resident-restore/{id}', 'Admin\ResidentTicketController@restore')->name('resident-tickets.restore');


            //dashboard setting routes
            Route::resource('guest-tickets', 'Admin\GuestTicketController')->middleware('checkGuardAdmin');
            Route::get('guest-tickets-data', 'Admin\GuestTicketController@guestTicketData')->name('guest-tickets-data');
            Route::post('guest-tickets-data', 'Admin\GuestTicketController@guestTicketData');
            Route::get('guest-ticket-details', 'Admin\GuestTicketController@ticketDetails')->name('guest-ticket-details');
            Route::get('guest-ticket-Images', 'Admin\GuestTicketController@ticketImages')->name('guest-ticket-images');
            Route::get('guest-email-templates', 'Admin\GuestTicketController@getTicketTemplatesByCommunity')->name('guest-email-templates');
            Route::post('guest-email-send', 'Admin\GuestTicketController@sendEmail')->name('guest-email-send');
            Route::post('guest-payment', 'Admin\GuestTicketController@payment')->name('guest-payment');
            Route::patch('guest-restore/{id}', 'Admin\GuestTicketController@restore')->name('guest-tickets.restore');


            //dashboard setting routes
            Route::resource('vendor-tickets', 'Admin\VendorTicketController')->middleware('checkGuardAdmin');
            Route::get('vendor-tickets-data', 'Admin\VendorTicketController@vendorTicketData')->name('vendor-tickets-data');
            Route::post('vendor-tickets-data', 'Admin\VendorTicketController@vendorTicketData');
            Route::get('vendor-ticket-details', 'Admin\VendorTicketController@ticketDetails')->name('vendor-ticket-details');
            Route::get('vendor-ticket-Images', 'Admin\VendorTicketController@ticketImages')->name('vendor-ticket-images');
            Route::get('vendor-email-templates', 'Admin\VendorTicketController@getTicketTemplatesByCommunity')->name('vendor-email-templates');
            Route::post('vendor-email-send', 'Admin\VendorTicketController@sendEmail')->name('vendor-email-send');
            Route::post('vendor-payment', 'Admin\VendorTicketController@payment')->name('vendor-payment');
            Route::patch('vendor-restore/{id}', 'Admin\VendorTicketController@restore')->name('vendor-tickets.restore');


            //dashboard setting routes
            Route::resource('unmatched-tickets', 'Admin\UnmatchedTicketController')->middleware('checkGuardAdmin');
            Route::get('unmatched-tickets-data', 'Admin\UnmatchedTicketController@unmatchedTicketData')->name('unmatched-tickets-data');
            Route::post('unmatched-tickets-data', 'Admin\UnmatchedTicketController@unmatchedTicketData');
            Route::get('unmatched-ticket-details', 'Admin\UnmatchedTicketController@ticketDetails')->name('unmatched-ticket-details');
            Route::get('unmatched-ticket-Images', 'Admin\UnmatchedTicketController@ticketImages')->name('unmatched-ticket-images');
            Route::post('unmatched-payment', 'Admin\UnmatchedTicketController@payment')->name('unmatched-payment');
            Route::post('unmatched-license-change', 'Admin\UnmatchedTicketController@changeLicense')->name('unmatched-license-change');

app/Models/OffensiveWord.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class OffensiveWord extends Model
{
    use SoftDeletes;
    protected $guarded = ['id'];

    public function community(){
        return $this->belongsTo(Community::class);
    }
}

app/Http/Controllers/Admin/OffensiveWordController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Services\OffensiveWordService;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\ValidationException;

class OffensiveWordController extends Controller
{
    public $offensiveWordService;
    protected $folderLink = 'admin.offensive-words.';

    public function __construct(OffensiveWordService $offensiveWordService)
    {
        $this->offensiveWordService = $offensiveWordService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        return view($this->folderLink . 'index');
    }

    /**
     * get offensive words list
     * @param Request $request
     * @return
     * @throws Exception
     */
    public function offensiveWordsData(Request $request)
    {
        return datatables()->of($this->offensiveWordService->all()['result'])
            ->addColumn('community_name', function ($model) {
                return $model->community->name ?? "";
            })
            ->editColumn('created_at', function ($model) {
                return (!empty($model->created_at)) ? $model->created_at->diffForHumans() : "-";
            })
            ->addColumn('edit_link', function ($model) {
                return '<a href="' . route('admin.settings.offensive-words.edit', [$model->id]) . '">Edit </a>';
            })
            ->rawColumns(['edit_link'])
            ->filter(function ($instance) use ($request) {
                if (isset($request->name)) {
                    $instance->where('name', 'like', "%{$request->get('name')}%");
                }
            })
            ->toJson();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     * @throws ValidationException
     */
    public function store(Request $request)
    {
        $validation = [
            'name' => 'required|unique:offensive_words',
        ];
        $messages = [
            'name.required' => 'Please enter word',
        ];
        $validator = Validator::make($request->all(), $validation, $messages);
        if ($validator->fails()) {
            $validator->validate();
        }
        $offensiveWordData = $request->all();
        $offensiveWordData['created_by'] = auth()->user()->id;
        $offensiveWordData['community_id'] = auth()->user()->community_id;

        $offensiveWord = $this->offensiveWordService->create($offensiveWordData);
        if ($offensiveWord['bool']) {
            // user activity logs
            callUserActivityLogs("Add Offensive Word", __FUNCTION__, __FILE__, __DIR__, true, "Added Successfully");

            $response = ['status' => true, 'message' => 'Added Successfully', 'redirect' => route('admin.settings.offensive-words.index')];
        } else {
            // user activity logs
            callUserActivityLogs("Add Offensive Word", __FUNCTION__, __FILE__, __DIR__, false, "Something went wrong. Please try again.");

            $response = ['status' => false, 'message' => 'Something went wrong. Please try again.'];
        }
        return response()->json($response);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     * @throws Exception
     */
    public function create()
    {
        return view($this->folderLink . 'create');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function edit($id)
    {
        $offensive_word = $this->offensiveWordService->find($id);
        if (!$offensive_word['bool']) {
            abort(500);
        }
        if (!$offensive_word['result']) {
            abort(404);
        }
        $data['offensive_word'] = $offensive_word['result'];
        return view($this->folderLink . 'edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $validation = [
            'name' => 'required|unique:offensive_words,name,' . $id,
        ];
        $messages = [
            'name.required' => 'Please enter word',
        ];
        $validator = Validator::make($request->all(), $validation, $messages);
        if ($validator->fails()) {
            $validator->validate();
        }
        $offensiveWordData = $request->all();
        $offensiveWordData['community_id'] = auth()->user()->community_id;

        $offensiveWord = $this->offensiveWordService->update($offensiveWordData, $id);
        if ($offensiveWord['bool']) {
            // user activity logs
            callUserActivityLogs("Edit Offensive Word", __FUNCTION__, __FILE__, __DIR__, true, "Update Successfully");

            $response = ['status' => true, 'message' => 'Update Successfully', 'redirect' => route('admin.settings.offensive-words.index')];
        } else {
            // user activity logs
            callUserActivityLogs("Edit Offensive Word", __FUNCTION__, __FILE__, __DIR__, false, "Something went wrong. Please try again.");

            $response = ['status' => false, 'message' => 'Something went wrong. Please try again.'];
        }
        return response()->json($response);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/offensive-words/create.blade.php
@extends('admin.layout.master')

@section('content')

    <style>
        .card-bg-heading {
            width: 100%;
            padding-right: 7.5px;
            padding-top: 10.5px;
            padding-bottom: 5px;
            padding-left: 7.5px;
            margin-right: auto;
            margin-left: auto;
            border: 2px solid #ede7e7;
            background: white !important;
            border-radius: 7px !important;
        }
    </style>

    <div class="content-wrapper">

        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2 card-bg-heading">
                    <div class="col-sm-6">
                        <h1>Add Word</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Add Offensive Word</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">
                                <a href="{{route('admin.settings.offensive-words.index')}}" class="add_advertiser">
                                    <i class="fas fa-list"></i> Go Back
                                </a>
                            </h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <form role="form" method="post" action="{{route('admin.settings.offensive-words.store')}}"
                                  class="ajax-form" enctype="multipart/form-data">
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="name">Offensive Word </label>
                                        <input type="text" name="name" id="name"
                                               placeholder="Offensive Word" class="form-control">
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">
                                        <!----> <span>Add </span>
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/admin/offensive-words/edit.blade.php
@extends('admin.layout.master')

@section('content')

    <style>
        .card-bg-heading {
            width: 100%;
            padding-right: 7.5px;
            padding-top: 10.5px;
            padding-bottom: 5px;
            padding-left: 7.5px;
            margin-right: auto;
            margin-left: auto;
            border: 2px solid #ede7e7;
            background: white !important;
            border-radius: 7px !important;
        }
    </style>

    <div class="content-wrapper">

        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2 card-bg-heading">
                    <div class="col-sm-6">
                        <h1>Edit Offensive Word</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Edit Offensive Word</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">
                                <a href="{{route('admin.settings.offensive-words.index')}}" class="add_advertiser">
                                    <i class="fas fa-list"></i> Go Back
                                </a>
                            </h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <form role="form" method="post"
                                  action="{{route('admin.settings.offensive-words.update', [$offensive_word->id])}}"
                                  class="ajax-form" enctype="multipart/form-data">
                                {{ method_field('PUT') }}
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="name">Offensive Word </label>
                                        <input type="text" name="name" id="name" placeholder="Offensive Word"
                                               class="form-control" value="{{$offensive_word->name}}">
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">
                                        <!----> <span>Save Changes </span>
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/admin/offensive-words/index.blade.php
@extends('admin.layout.master')
@section('content')

    <style>
        .card-bg-heading {
            width: 100%;
            padding-right: 7.5px;
            padding-top: 10.5px;
            padding-bottom: 5px;
            padding-left: 7.5px;
            margin-right: auto;
            margin-left: auto;
            border: 2px solid #ede7e7;
            background: white !important;
            border-radius: 7px !important;
        }
    </style>
    <div class="content-wrapper">

        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2 card-bg-heading">
                    <div class="col-sm-6">
                        <h1>Offensive Words</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Offensive Words</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <!-- Default box -->
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Search Filter</h3>
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse"
                                            title="Collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="card-body">
                                <form role="form" method="get" id="search-filter">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label for="name">Name</label>
                                                <input type="text" name="name" id="name" placeholder="Name"
                                                       class="form-control">
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <button type="button" class="btn btn-primary search-btn">
                                    <span>Search </span>
                                </button>
                            </div>
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
            </div>
        </section>
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">
                                <a href="{{route('admin.settings.offensive-words.create')}}" class="add_advertiser">
                                    <i class="fas fa-plus-circle"></i> Create Words
                                </a>
                            </h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body table-responsive">
                            <table id="AnnouncementsTable" class="table  table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Word</th>
                                    <th>Created At</th>
                                    <th>Action(s)</th>
                                </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection
@push('scripts')
    <script>
        let columns = [
            {
                data: 'id',
            },
            {
                data: 'name',
            },
            {
                data: 'created_at',
            },
            {
                data: function (data) {
                    return data.edit_link;
                }
            },
        ];
        zuulDataTableSortable('#AnnouncementsTable', "{{route('admin.settings.offensive-words-data')}}", columns, [3]);

        $('.search-btn').click(function () {
            var ajax = "{{route('admin.settings.offensive-words-data')}}?" + $("#search-filter").serialize();
            zuulDataTableSortable('#AnnouncementsTable', ajax, columns, [3]);
        })
    </script>
@endpush