routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('create-quick-pass', 'API\GuardController@createQuickPass2');


Route::get('/reset-app', function () {
    $code = request()->input('code') ?? "";
    return view('auth.reset_password')->with('code', $code);
})->name('reset-app');
Route::get('testings', 'Frontend\TestController@index')->name('testing');
Route::get('fire-base-testing', 'Frontend\TestController@index')->name('fire-base-testing');

Route::get('/clear_cache', function () {
    $exitCode = Illuminate\Support\Facades\Artisan::call('cache:clear');
    $exitCode .= Illuminate\Support\Facades\Artisan::call('view:clear');
});
Route::get('ring-central', 'API\RingCentralController@viewLoad');
Route::get('ring-central-voice-messages', 'API\RingCentralController@ringCentralVoiceMessageView');

Route::get('nd/{notificationId}', 'Frontend\DashboardController@notificationDetail')->name('notification-detail');
Route::get('notification-submit', 'Frontend\DashboardController@notificationSubmit')->name('notification-submit');
Route::get('anonymous-request-a-pass', 'Frontend\FrontendPassRequestController@index')->name('anonymous-request-a-pass');
Route::post('anonymous-request-a-pass-submit', 'Frontend\FrontendPassRequestController@store')->name('anonymous-request-a-pass-submit');

Route::resource('two-factor-verification', 'TwoFactorVerification');

Route::get('password-reset', 'Frontend\PasswordController@passwordReset')->name('password-reset');
Route::post('password-reset-save', 'Frontend\PasswordController@passwordResetPost')->name('password-reset-save');

// new addition reset password @mazhar
Route::post('reset-password', 'Admin\UserController@resetPassword');


Route::get('get-contact-in-dnc-by-resident-id/{id}', 'API\UserContactsController@getContactInDncByResidentId2')->name('dnc-by-resident');

//admin routes
Route::group(['middleware' => ['auth:web', 'admin', 'adminDeactivate'], 'prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::post('get-remote-guard-keys', 'Admin\RemoteGuardController@getRemoteGuardKeys')->name('get-remote-guard-keys');


    Route::get('/', 'Admin\DashboardController@index')->name('dashboard')->middleware('checkGuardAdmin');
    Route::get('/dashboard', 'Admin\DashboardController@index')->name('dashboard')->middleware('checkGuardAdmin');

    Route::resource('dashboard-setting', 'Admin\DashboardSettingController')->middleware('checkGuardAdmin');

    Route::resource('connected-pi', 'Admin\ConnectedPiController');
    Route::get('connected-pi-data', 'Admin\ConnectedPiController@connectedPiData')->name('connected-pi-data');
    Route::resource('passes', 'Admin\PassController');
    Route::get('passes-data', 'Admin\PassController@passesData')->name('passes-data');
    Route::post('pass-recipients', 'Admin\PassController@passRecipients')->name('pass-recipients');

    Route::resource('network', 'Admin\NetworkController');
    Route::get('network-data', 'Admin\NetworkController@networkData')->name('network-data');

    Route::resource('remote-guard', 'Admin\RemoteGuardController');
    Route::get('remote-guard-data', 'Admin\RemoteGuardController@remoteGuardData')->name('remote-guard-data');

    Route::group(['middleware' => 'checkKiosk'], function () {

        Route::get('queuejob', function () {
            Artisan::call('queue:work');
        });
        // Profile
        Route::resource('password', 'Admin\PasswordController');
        Route::resource('profile', 'Admin\ProfileController');

        Route::resource('pre-approved', 'Admin\PreApproveController');
        Route::get('pre-approved-data', 'Admin\PreApproveController@preApprovedData')->name('pre-approved-data');

        Route::resource('iono-heartbeat', 'Admin\IonoHeartbeatLogController');
        Route::get('iono-heartbeat-logs-data', 'Admin\IonoHeartbeatLogController@ionoHeartbeatLogsData')->name('iono-heartbeat-logs-data');

        //csv notifications
        Route::post('csv-notifications', 'Admin\DashboardController@csvNotifications')->name('csv-notifications');
        Route::post('csv-notification-viewed', 'Admin\DashboardController@csvNotificationViewed')->name('csv-notification-viewed');

    });

    //users routes
    Route::group(['prefix' => 'user', 'as' => 'user.'], function () {

        //guests routes
        Route::resource('guests', 'Admin\UserController')->middleware(['checkGuardAdmin']);
        Route::get('/banned-guests', 'Admin\UserController@bandGuest')->middleware(['checkGuardAdmin'])->name('banned-guests'); // 'checkCommunityAdmin',

        Route::post('/add-banned-user', 'Admin\UserController@addbandGuest')->middleware(['checkGuardAdmin'])->name('add-banned-user');
        Route::get('/banned-user', 'Admin\UserController@addbandGuestForm')->name('add-banned-user-form');
        Route::get('/guest-data', 'Admin\UserController@guestData')->name('guest-data');
        Route::get('/guest-band-data', 'Admin\UserController@guestBandData')->name('guest-band-data');
        Route::get('/get-community-list', 'Admin\UserController@getCommunity')->middleware(['checkGuardAdmin'])->name('get-community-list');
        Route::post('resend-temporary-password-guest/{id}', 'Admin\UserController@resendTemporaryPassword')->name('resend-temporary-password-guest');
        //revoke resident
        Route::post('revoke-resident', 'Admin\UserController@revokeResident')->name('revoke-resident');
        Route::post('delete-guest/{userId}', 'Admin\UserController@deleteGuest')->name('delete-guest');

        Route::post('check-guest-permission', 'Admin\UserController@checkGuestPermission')->name('check-guest-permission');
        Route::post('check-banned-permission', 'Admin\UserController@checkBannedPermission')->name('check-banned-permission');

        Route::post('assign-banned-permission', 'Admin\UserController@assignBannedPermission')->name('assign-banned-permission');
        Route::post('assign-guest-permission', 'Admin\UserController@assignGuestPermission')->name('assign-guest-permission');
        Route::post('make-resident', 'Admin\UserController@makeResident')->name('make-resident');
        Route::post('get-user', 'Admin\UserController@getUser')->name('get-user');
        Route::post('suspend-guest/{userId}', 'Admin\UserController@suspendGuest')->name('suspend-guest');
        Route::post('unsuspend-guest/{userId}', 'Admin\UserController@unsuspendGuest')->name('unsuspend-guest');

        //community admins routes
        Route::resource('/community-admins', 'Admin\CommunityAdminController')->middleware('checkGuardAdmin');
        Route::get('/community-admins-data', 'Admin\CommunityAdminController@communityAdminsData')->name('community-admins-data');
        Route::post('delete-community-admin/{userId}', 'Admin\CommunityAdminController@deleteCommunityAdmin')->name('delete-community-admin');
        Route::post('deactivate-admin-status', 'Admin\CommunityAdminController@deactivateCommunityAdmin')->name('deactivate-community-admin');
        Route::post('activate-admin-status', 'Admin\CommunityAdminController@activateCommunityAdmin')->name('activate-community-admin');

        Route::group(['middleware' => 'checkKiosk'], function () {

            //Mark:- Kiosk Admin Routes
            Route::resource('/kiosk-admins', 'Admin\KioskAdminController')->middleware('checkGuardAdmin');
            Route::get('/kiosk-admins-data', 'Admin\KioskAdminController@kioskAdminsData')->name('kiosk-admins-data');
            Route::post('delete-kiosk-admin/{userId}', 'Admin\KioskAdminController@deleteKioskAdmin')->name('delete-kiosk-admin');
            Route::post('deactivate-kiosk-status', 'Admin\KioskAdminController@deactivateKioskAdmin')->name('deactivate-kiosk-admin');
            Route::post('activate-kiosk-status', 'Admin\KioskAdminController@activateKioskAdmin')->name('activate-kiosk-admin');

        });

        //security guards routes
        Route::resource('guards', 'Admin\GuardController')->middleware('checkGuardAdmin');
        Route::get('/guards-data', 'Admin\GuardController@guardData')->name('guards-data');

        Route::group(['middleware' => 'checkKiosk'], function () {

            Route::post('/send-reset-link', 'Admin\GuardController@sendResetLink')->name('send-reset-link');
            Route::post('/check-guard-permission', 'Admin\GuardController@checkGuardPermission')->name('check-guard-permission');
            Route::post('/guard-permission', 'Admin\GuardController@guardPermission')->name('guard-permission');
            Route::post('delete-guard/{userId}', 'Admin\GuardController@deleteGuard')->name('delete-guard');
            Route::post('deactivate-guard-status', 'Admin\GuardController@deactivateGuard')->name('deactivate-guard');
            Route::post('activate-guard-status', 'Admin\GuardController@activateGuard')->name('activate-guard');
            //revoke guard
            Route::post('revoke-guard', 'Admin\GuardController@revokeGuard')->name('revoke-guard');
            Route::post('resend-guard-verification-code', 'Admin\GuardController@resendGuardVerificationCode')->name('resend-guard-verification-code');

            Route::group(['prefix' => 'guard-appoint', 'as' => 'guard-appoint.'], function () {
                Route::resource('appoint-locations', 'Admin\GuardAppointLocationController')->middleware('checkGuardAdmin');
                Route::get('guard-appoint-location-data', 'Admin\GuardAppointLocationController@guardAppointLocationData')->name('guard-appoint-location-data');
            });
        });

    });


    //residential prefix

resources/views/admin/users/community-admins/create.blade.php
@extends('admin.layout.master')
@section('content')

    <style>
        .card-bg-heading {
            width: 100%;
            padding-right: 7.5px;
            padding-top: 10.5px;
            padding-bottom: 5px;
            padding-left: 7.5px;
            margin-right: auto;
            margin-left: auto;
            border: 2px solid #ede7e7;
            background: white !important;
            border-radius: 7px !important;
        }
    </style>


    <div class="content-wrapper">

        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2 card-bg-heading">
                    <div class="col-sm-6">
                        <h1>Add Community Admin</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Add Community Admin</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">
                                <a href="{{route('admin.user.community-admins.index')}}" class="add_advertiser">
                                    <i class="fas fa-list"></i> Go Back
                                </a>
                            </h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <form role="form" method="post" action="{{route('admin.user.community-admins.store')}}"
                                  class="ajax-form" enctype="multipart/form-data">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label for="first_name">First Name </label>
                                                <input type="text" name="first_name" id="first_name"
                                                       placeholder="First Name" class="form-control">
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label for="last_name">Last Name </label>
                                                <input type="text" name="last_name" id="last_name"
                                                       placeholder="Last Name" class="form-control">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label for="email">Email </label>
                                                <input type="text" name="email" id="email"
                                                       placeholder="Email" class="form-control">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="dial_code">Country code</label>
                                                @php
                                                    $url = route('get-phone-format-by-dial-code');
                                                @endphp
                                                <select
                                                    id="dial_code" name="dial_code" class="form-control select2bs4"
                                                    onchange="changePhoneDigitsFormat1('{{ $url }}')">
                                                    @foreach($countries as $country)
                                                        <option
                                                            value="+{{$country->dial_code}}">{{$country->country_name}}
                                                            +{{$country->dial_code}}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="phone_number">Phone Number</label>
                                                <input type="text" class="form-control" name="phone_number"
                                                       id="phone_number">
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="community_id">Community Assigned</label>
                                                <select
                                                    id="community_id" name="community_id"
                                                    class="form-control select2bs4">
                                                    <option value="">Select Community</option>
                                                    @foreach($communities as $community)
                                                        <option value="{{$community->id}}">{{$community->name}}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label for="profile_image">Profile Image</label>
                                                <input type="file" name="profile_image" id="profile_image" class=""
                                                       accept='image/*'/>
                                                <div class="help-block">Upload Profile Picture.</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">
                                        <!----> <span>Add </span>
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection
@push('scripts')
    <script>
        $(document).ready(function () {
            var $phoneFormat = "999-999-9999";
            $('#phone_number').inputmask({mask: $phoneFormat});
        });
    </script>
@endpush

resources/views/admin/users/community-admins/edit.blade.php
@extends('admin.layout.master')
@section('content')

    <style>
        .card-bg-heading {
            width: 100%;
            padding-right: 7.5px;
            padding-top: 10.5px;
            padding-bottom: 5px;
            padding-left: 7.5px;
            margin-right: auto;
            margin-left: auto;
            border: 2px solid #ede7e7;
            background: white !important;
            border-radius: 7px !important;
        }
    </style>
    <div class="content-wrapper">

        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2 card-bg-heading">
                    <div class="col-sm-6">
                        <h1>Edit Community Admin</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Edit Community Admin</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">
                                <a href="{{route('admin.user.community-admins.index')}}" class="add_advertiser">
                                    <i class="fas fa-list"></i> Go Back
                                </a>
                            </h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <form role="form" method="post"
                                  action="{{route('admin.user.community-admins.update', [$community_admin->id])}}"
                                  class="ajax-form" enctype="multipart/form-data">
                                {{ method_field('PUT') }}
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label for="first_name">First Name </label>
                                                <input type="text" name="first_name" id="first_name"
                                                       placeholder="First Name" class="form-control"
                                                       value="{{$community_admin->first_name}}">
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label for="last_name">Last Name </label>
                                                <input type="text" name="last_name" id="last_name"
                                                       placeholder="Last Name" class="form-control"
                                                       value="{{$community_admin->last_name}}">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label for="email">Email </label>
                                                <input type="text" name="email" id="email" placeholder="Email"
                                                       class="form-control" value="{{$community_admin->email}}">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="dial_code">Country code</label>
                                                @php
                                                    $url = route('get-phone-format-by-dial-code')
                                                @endphp
                                                <select id="dial_code" name="dial_code" class="form-control select2bs4"
                                                        onchange="changePhoneDigitsFormat1('{{ $url }}')">
                                                    @foreach($countries as $country)
                                                        <option value="+{{$country->dial_code}}"
                                                                @if($country->dial_code == $community_admin->dial_code)selected="true"@endif>{{$country->country_name}}
                                                            +{{$country->dial_code}}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="phone_number">Phone Number</label>
                                                <input type="text" class="form-control"
                                                       value="{{$community_admin->phone_number}}" name="phone_number"
                                                       id="phone_number">
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="community_id">Community Assigned</label>
                                                <select id="community_id" name="community_id"
                                                        class="form-control select2bs4">
                                                    <option value="">Select Community</option>
                                                    @foreach($communities as $community)
                                                        <option value="{{$community->id}}"
                                                                @if($community->id == $community_admin->community_id)selected="true"@endif>{{$community->name}}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label for="profile_image">Profile Image</label>
                                                <input type="file" name="profile_image" id="profile_image" class=""
                                                       accept='image/*'/>
                                                <div class="help-block">Upload Profile Picture.</div>
                                                <img src="{{$community_admin->profile_image_url}}" style="width: 100px">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">
                                        <!----> <span>Save </span>
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection
@push('scripts')
    <script>
        $(document).ready(function () {
            var $formattedPhone = "{{ $phoneFormat }}";
            $('#phone_number').inputmask({mask: $formattedPhone});
        });
    </script>
@endpush