routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('create-quick-pass', 'API\GuardController@createQuickPass2');


Route::get('/reset-app', function () {
    $code = request()->input('code') ?? "";
    return view('auth.reset_password')->with('code', $code);
})->name('reset-app');
Route::get('testings', 'Frontend\TestController@index')->name('testing');
Route::get('fire-base-testing', 'Frontend\TestController@index')->name('fire-base-testing');

Route::get('/clear_cache', function () {
    $exitCode = Illuminate\Support\Facades\Artisan::call('cache:clear');
    $exitCode .= Illuminate\Support\Facades\Artisan::call('view:clear');
});
Route::get('ring-central', 'API\RingCentralController@viewLoad');
Route::get('ring-central-voice-messages', 'API\RingCentralController@ringCentralVoiceMessageView');

Route::get('nd/{notificationId}', 'Frontend\DashboardController@notificationDetail')->name('notification-detail');
Route::get('notification-submit', 'Frontend\DashboardController@notificationSubmit')->name('notification-submit');
Route::get('anonymous-request-a-pass', 'Frontend\FrontendPassRequestController@index')->name('anonymous-request-a-pass');
Route::post('anonymous-request-a-pass-submit', 'Frontend\FrontendPassRequestController@store')->name('anonymous-request-a-pass-submit');

Route::resource('two-factor-verification', 'TwoFactorVerification');

Route::get('password-reset', 'Frontend\PasswordController@passwordReset')->name('password-reset');
Route::post('password-reset-save', 'Frontend\PasswordController@passwordResetPost')->name('password-reset-save');

// new addition reset password @mazhar
Route::post('reset-password', 'Admin\UserController@resetPassword');


Route::get('get-contact-in-dnc-by-resident-id/{id}', 'API\UserContactsController@getContactInDncByResidentId2')->name('dnc-by-resident');

//admin routes
Route::group(['middleware' => ['auth:web', 'admin', 'adminDeactivate'], 'prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::post('get-remote-guard-keys', 'Admin\RemoteGuardController@getRemoteGuardKeys')->name('get-remote-guard-keys');


    Route::get('/', 'Admin\DashboardController@index')->name('dashboard')->middleware('checkGuardAdmin');
    Route::get('/dashboard', 'Admin\DashboardController@index')->name('dashboard')->middleware('checkGuardAdmin');

    Route::resource('dashboard-setting', 'Admin\DashboardSettingController')->middleware('checkGuardAdmin');

    Route::resource('connected-pi', 'Admin\ConnectedPiController');
    Route::get('connected-pi-data', 'Admin\ConnectedPiController@connectedPiData')->name('connected-pi-data');
    Route::resource('passes', 'Admin\PassController');
    Route::get('passes-data', 'Admin\PassController@passesData')->name('passes-data');
    Route::post('pass-recipients', 'Admin\PassController@passRecipients')->name('pass-recipients');

    Route::resource('network', 'Admin\NetworkController');
    Route::get('network-data', 'Admin\NetworkController@networkData')->name('network-data');

    Route::resource('remote-guard', 'Admin\RemoteGuardController');
    Route::get('remote-guard-data', 'Admin\RemoteGuardController@remoteGuardData')->name('remote-guard-data');

    Route::group(['middleware' => 'checkKiosk'], function () {

        Route::get('queuejob', function () {
            Artisan::call('queue:work');
        });
        // Profile
        Route::resource('password', 'Admin\PasswordController');
        Route::resource('profile', 'Admin\ProfileController');

        Route::resource('pre-approved', 'Admin\PreApproveController');
        Route::get('pre-approved-data', 'Admin\PreApproveController@preApprovedData')->name('pre-approved-data');

        Route::resource('iono-heartbeat', 'Admin\IonoHeartbeatLogController');
        Route::get('iono-heartbeat-logs-data', 'Admin\IonoHeartbeatLogController@ionoHeartbeatLogsData')->name('iono-heartbeat-logs-data');

        //csv notifications
        Route::post('csv-notifications', 'Admin\DashboardController@csvNotifications')->name('csv-notifications');
        Route::post('csv-notification-viewed', 'Admin\DashboardController@csvNotificationViewed')->name('csv-notification-viewed');

    });

    //users routes
    Route::group(['prefix' => 'user', 'as' => 'user.'], function () {

        //guests routes
        Route::resource('guests', 'Admin\UserController')->middleware(['checkGuardAdmin']);
        Route::get('/banned-guests', 'Admin\UserController@bandGuest')->middleware(['checkGuardAdmin'])->name('banned-guests'); // 'checkCommunityAdmin',

        Route::post('/add-banned-user', 'Admin\UserController@addbandGuest')->middleware(['checkGuardAdmin'])->name('add-banned-user');
        Route::get('/banned-user', 'Admin\UserController@addbandGuestForm')->name('add-banned-user-form');
        Route::get('/guest-data', 'Admin\UserController@guestData')->name('guest-data');
        Route::get('/guest-band-data', 'Admin\UserController@guestBandData')->name('guest-band-data');
        Route::get('/get-community-list', 'Admin\UserController@getCommunity')->middleware(['checkGuardAdmin'])->name('get-community-list');
        Route::post('resend-temporary-password-guest/{id}', 'Admin\UserController@resendTemporaryPassword')->name('resend-temporary-password-guest');
        //revoke resident
        Route::post('revoke-resident', 'Admin\UserController@revokeResident')->name('revoke-resident');
        Route::post('delete-guest/{userId}', 'Admin\UserController@deleteGuest')->name('delete-guest');

        Route::post('check-guest-permission', 'Admin\UserController@checkGuestPermission')->name('check-guest-permission');
        Route::post('check-banned-permission', 'Admin\UserController@checkBannedPermission')->name('check-banned-permission');

        Route::post('assign-banned-permission', 'Admin\UserController@assignBannedPermission')->name('assign-banned-permission');
        Route::post('assign-guest-permission', 'Admin\UserController@assignGuestPermission')->name('assign-guest-permission');
        Route::post('make-resident', 'Admin\UserController@makeResident')->name('make-resident');
        Route::post('get-user', 'Admin\UserController@getUser')->name('get-user');
        Route::post('suspend-guest/{userId}', 'Admin\UserController@suspendGuest')->name('suspend-guest');
        Route::post('unsuspend-guest/{userId}', 'Admin\UserController@unsuspendGuest')->name('unsuspend-guest');

        //community admins routes
        Route::resource('/community-admins', 'Admin\CommunityAdminController')->middleware('checkGuardAdmin');
        Route::get('/community-admins-data', 'Admin\CommunityAdminController@communityAdminsData')->name('community-admins-data');
        Route::post('delete-community-admin/{userId}', 'Admin\CommunityAdminController@deleteCommunityAdmin')->name('delete-community-admin');
        Route::post('deactivate-admin-status', 'Admin\CommunityAdminController@deactivateCommunityAdmin')->name('deactivate-community-admin');
        Route::post('activate-admin-status', 'Admin\CommunityAdminController@activateCommunityAdmin')->name('activate-community-admin');

        Route::group(['middleware' => 'checkKiosk'], function () {

            //Mark:- Kiosk Admin Routes
            Route::resource('/kiosk-admins', 'Admin\KioskAdminController')->middleware('checkGuardAdmin');
            Route::get('/kiosk-admins-data', 'Admin\KioskAdminController@kioskAdminsData')->name('kiosk-admins-data');
            Route::post('delete-kiosk-admin/{userId}', 'Admin\KioskAdminController@deleteKioskAdmin')->name('delete-kiosk-admin');
            Route::post('deactivate-kiosk-status', 'Admin\KioskAdminController@deactivateKioskAdmin')->name('deactivate-kiosk-admin');
            Route::post('activate-kiosk-status', 'Admin\KioskAdminController@activateKioskAdmin')->name('activate-kiosk-admin');

        });

        //security guards routes
        Route::resource('guards', 'Admin\GuardController')->middleware('checkGuardAdmin');
        Route::get('/guards-data', 'Admin\GuardController@guardData')->name('guards-data');

        Route::group(['middleware' => 'checkKiosk'], function () {

            Route::post('/send-reset-link', 'Admin\GuardController@sendResetLink')->name('send-reset-link');
            Route::post('/check-guard-permission', 'Admin\GuardController@checkGuardPermission')->name('check-guard-permission');
            Route::post('/guard-permission', 'Admin\GuardController@guardPermission')->name('guard-permission');
            Route::post('delete-guard/{userId}', 'Admin\GuardController@deleteGuard')->name('delete-guard');
            Route::post('deactivate-guard-status', 'Admin\GuardController@deactivateGuard')->name('deactivate-guard');
            Route::post('activate-guard-status', 'Admin\GuardController@activateGuard')->name('activate-guard');
            //revoke guard
            Route::post('revoke-guard', 'Admin\GuardController@revokeGuard')->name('revoke-guard');
            Route::post('resend-guard-verification-code', 'Admin\GuardController@resendGuardVerificationCode')->name('resend-guard-verification-code');

            Route::group(['prefix' => 'guard-appoint', 'as' => 'guard-appoint.'], function () {
                Route::resource('appoint-locations', 'Admin\GuardAppointLocationController')->middleware('checkGuardAdmin');
                Route::get('guard-appoint-location-data', 'Admin\GuardAppointLocationController@guardAppointLocationData')->name('guard-appoint-location-data');
            });
        });

    });


    //residential prefix

app/Http/Controllers/Frontend/AccountSettingsController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\CountryPhoneFormat;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Requests\AccountSettingsRequest;
use App\Services\UserService;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Storage;
use App\Models\Country;
use Intervention\Image\Facades\Image;
use App\Services\HouseService;



class AccountSettingsController extends Controller
{
    protected $folderLink = 'frontend.accountsettings.';
    public $userService;
    public $houseService;

    public function __construct(UserService $userService, HouseService $houseService)
    {
        $this->userService = $userService;
        $this->houseService = $houseService;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data["countries"] = Country::all();
        $countryPhoneFormat = CountryPhoneFormat::where('dial_code',auth()->user()->dial_code)->first();
        $data['phoneFormat'] = "999-999-9999";
        if(!empty($countryPhoneFormat))
        {
            $data['phoneFormat'] = $countryPhoneFormat->format;
        }

        return view($this->folderLink.'index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    //Have to update images
    public function update(AccountSettingsRequest $request, $id)
    {
        //
        $userData = Arr::except($request->all(), ['profile_image']);
        //upload profile picture
        if ($request->hasFile('profile_image'))
        {

            $image = $request->file('profile_image');
            $userData['profile_image'] = 'profile_'.time().'.'.$image->getClientOriginalExtension();

            $destinationPath = public_path('images/profile_images');
            $img = Image::make($image->getRealPath());
            $img->save($destinationPath.'/'.$userData['profile_image'], 10);
        }

        //upload license image to s3 bucket
        if ($request->hasFile('license_image'))
        {
            $image = $request->file('license_image');
            $licenseImage = Image::make($image->getRealPath());
            $licenseImagea =  $licenseImage->stream(null,10);
            $licenceName = md5(uniqid()) . '.' . 'png';
            $filePath =  "dynamic/lic_images/".$licenceName;
            $path = Storage::disk('s3')->put($filePath, $licenseImagea);
            if (!$path){
                return  response()->json(['status' => false, 'message' => 'Something went wrong.Please try again.']);
            }
            $userData['license_image'] = $filePath;
        } else {
            $userData['license_image'] = $request->old_license_image;
        }
        if (!auth()->user()->hasPermission('is_license_locked')){
            auth()->user()->assignPermission('is_license_locked');
        }
        if (auth()->user()->hasPermission('is_license_locked')){
            unset( $userData['license_image']);
        }
        unset( $userData['phone_number']);

        $user = $this->userService->update($userData,$id);

        $houseId = $this->userService->find($id)['result']->house_id;

        $houseCompletedProfileStatus = "no";
        $houseResidents = User::where('house_id', $houseId)->whereIn('role_id', [4, 5])->get();
        foreach ($houseResidents as $houseResident)
        {
            if(!empty($houseResident->license_image))
            {
                $houseCompletedProfileStatus = "yes";
            }
        }

        $this->houseService->update(['completed_profile'=>$houseCompletedProfileStatus], $houseId);

        if ($user['bool']) {
            $response = ['status' => true, 'message' => 'Updated Successfully', 'redirect' => route('account-setting.index')];
        }
        else {
            $response = ['status' => false, 'message' => 'Something went wrong.Please try again.'];
        }
        return response()->json($response);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Frontend/ArchivePassController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Http\Resources\ActivePassCollection;
use App\Http\Resources\ActivePassDateCollection;
use App\Services\PassService;
use App\Services\PassUserService;
use App\Services\UserService;
use Illuminate\Http\Request;

class ArchivePassController extends Controller
{
    protected $folderLink = 'frontend.passes.archived-passes.';

    public $passService;
    public $passUserService;
    public $userService;

    public function __construct(
        PassService $passService,
        PassUserService $passUserService,
        UserService $userService

    )
    {
        $this->userService = $userService;
        $this->passService = $passService;
        $this->passUserService = $passUserService;
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data['userId'] = $request->userId ?? "";
        return view($this->folderLink . 'index',$data);
    }

    /**
     * get user scanned passes
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function scannedPassesData(Request $request)
    {
        $userId = auth()->id();
        if (!empty($request->userId)){
            $userId = $request->userId;
            $user = $this->userService->find($userId)['result'];
            if (!empty($user) &&   $user->house_id != auth()->user()->house_id){
                $userId = null;
            }
        }
        $search = $request->search ?? "";
        $filter_type = $request->filter_type ?? "";
        $filter_search = $request->filter_search ?? "";
        $data = $this->passUserService->getScannedPassUserByUser($userId,$search,$filter_type,$filter_search,10);
        return response()->json([
            'data' =>  ActivePassCollection::collection($data['result'])
        ]);
    }

    /**
     * get scanned passes Dates for filter records
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function scannedPassesDates(Request $request){
        $userId = auth()->id();
        if (!empty($request->userId)){
            $userId = $request->userId;
            $user = $this->userService->find($userId)['result'];
            if (!empty($user) &&   $user->house_id != auth()->user()->house_id){
                $userId = null;
            }
        }
        $data = $this->passUserService->getScannedPassUserDatesByUser($userId);
        return response()->json([
            'data' =>  ActivePassDateCollection::collection($data['result'])
        ]);
    }

}

resources/views/frontend/pre-approved/create.blade.php
@extends('frontend.layout.master')
@section('content')
    <div class="container-fluid">

        <!-- Page Heading -->
        <p class="mb-4">Home / PreApproved / Add</p>

        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <a href="{{route('pre-approved.index')}}" class="add_advertiser">
                    <i class="fas fa-list"></i> Pre Approved
                </a>
            </div>
            <div class="card-body">
                <div class="card-body">
                    <form role="form" method="post" action="{{route('pre-approved.store')}}"
                          class="ajax-form" enctype="multipart/form-data">
                        <div class="card-body">
                            <div class="row" id="temporary-contact-div" style="display: none">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="temporary_duration">Contact Duration</label>
                                        <select name="temporary_duration" id="temporary_duration" class="form-control">
                                            <option value="6" selected="">6 Hours</option>
                                            <option value="12">12 Hours</option>
                                            <option value="24">24 Hours</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="contact_name">Contact Name</label>
                                        <input type="text" name="contact_name" id="contact_name"
                                               placeholder="Contact Name"
                                               class="form-control">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Shared</label>
                                        <select class="form-control" name="is_dnc_shared">
                                            <option value="0">No</option>
                                            <option value="1">Yes</option>
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="dial_code">Country code</label>
                                        <select name="dial_code" class="form-control dial_code"
                                                onchange="changePhoneDigitsFormat()">
                                            @foreach($countries as $country)
                                                <option value="{{$country->dial_code}}">{{$country->country_name}}
                                                    +{{$country->dial_code}}</option>
                                            @endforeach
                                        </select>

                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="phone_number">Phone Number</label>
                                        <input type="text" name="phone_number" class="form-control"
                                               placeholder="Phone Number" id="phone_number"/>

                                    </div>
                                </div>
                            </div>


                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">
                                <!----> <span>Add </span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>
@endsection
@push('scripts')
    <script>

        $(document).ready(function () {
            $('#phone_number').inputmask({mask: "999-999-9999"});

            $('.dial_code').change(function () {

                $.ajax({
                    url: "{{ route("get-phone-format-by-dial-code") }}",
                    type: "POST",
                    data: {dial_code: $(this).val()},
                    dataType: "JSON",
                    success: function (result) {
                        if (result.countryPhoneFormat != null) {
                            $('#phone_number').inputmask({mask: result.countryPhoneFormat.format});
                        } else {
                            $('#phone_number').inputmask({mask: '999-999-9999'});
                        }
                    }
                });

            });
        });


    </script>
@endpush

resources/views/frontend/pre-approved/edit.blade.php
@extends('frontend.layout.master')
@section('content')
    <div class="container-fluid">

        <!-- Page Heading -->
        <p class="mb-4">Home / Pre-Approved Guests / Edit</p>

        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <a href="{{route('pre-approved.index')}}" class="add_advertiser">
                    <i class="fas fa-list"></i> Pre-Approved Guest
                </a>
            </div>
            <div class="card-body">
                <div class="card-body">
                    <form role="form" method="post" action="{{route('pre-approved.update',$userContact->id)}}"
                          class="ajax-form" enctype="multipart/form-data">
                        @method('PUT')
                        <div class="card-body">
                            <div class="row" id="temporary-contact-div" style="display: none">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="temporary_duration">Contact Duration</label>
                                        <select name="temporary_duration" id="temporary_duration" class="form-control">
                                            <option value="6" selected="">6 Hours</option>
                                            <option value="12">12 Hours</option>
                                            <option value="24">24 Hours</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="contact_name">Contact Name</label>
                                        <input type="text" name="contact_name" id="contact_name"
                                               placeholder="Contact Name"
                                               class="form-control" value="{{ $userContact->contact_name }}">
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Shared</label>
                                        <select class="form-control" name="is_dnc_shared">
                                            <option
                                                value="0" {{ $userContact->is_dnc_shared == "0" ? "selected" : "" }}>No
                                            </option>
                                            <option
                                                value="1" {{ $userContact->is_dnc_shared == "1" ? "selected" : "" }}>Yes
                                            </option>
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="dial_code">Country code</label>
                                        <select name="dial_code" class="form-control dial_code"
                                                onchange="changePhoneDigitsFormat()">
                                            @foreach($countries as $country)
                                                <option
                                                    value="{{$country->dial_code}}" {{ $country->dial_code == $userContact->contact->dial_code ? 'selected' : ''  }}>{{$country->country_name}}
                                                    +{{$country->dial_code}}</option>
                                            @endforeach
                                        </select>

                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="phone_number">Phone Number</label>

                                        <input type="text" name="phone_number" class="form-control"
                                               placeholder="Phone Number"
                                               value="{{ $userContact->contact->phone_number }}" id="phone_number"/>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">
                                <!----> <span>Save </span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>
@endsection
@push('scripts')
    <script>


        $(document).ready(function () {
            var $phoneFormat = "{{ $phoneFormat }}";
            $('#phone_number').inputmask({mask: $phoneFormat})

            $('.dial_code').change(function () {

                $.ajax({
                    url: "{{ route("get-phone-format-by-dial-code") }}",
                    type: "POST",
                    data: {dial_code: $(this).val()},
                    dataType: "JSON",
                    success: function (result) {
                        if (result.countryPhoneFormat != null) {
                            $('#phone_number').inputmask({mask: result.countryPhoneFormat.format});
                        } else {
                            $('#phone_number').inputmask({mask: '999-999-9999'});
                        }
                    }
                });

            });

        });
    </script>
@endpush