routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('create-quick-pass', 'API\GuardController@createQuickPass2');


Route::get('/reset-app', function () {
    $code = request()->input('code') ?? "";
    return view('auth.reset_password')->with('code', $code);
})->name('reset-app');
Route::get('testings', 'Frontend\TestController@index')->name('testing');
Route::get('fire-base-testing', 'Frontend\TestController@index')->name('fire-base-testing');

Route::get('/clear_cache', function () {
    $exitCode = Illuminate\Support\Facades\Artisan::call('cache:clear');
    $exitCode .= Illuminate\Support\Facades\Artisan::call('view:clear');
});
Route::get('ring-central', 'API\RingCentralController@viewLoad');
Route::get('ring-central-voice-messages', 'API\RingCentralController@ringCentralVoiceMessageView');

Route::get('nd/{notificationId}', 'Frontend\DashboardController@notificationDetail')->name('notification-detail');
Route::get('notification-submit', 'Frontend\DashboardController@notificationSubmit')->name('notification-submit');
Route::get('anonymous-request-a-pass', 'Frontend\FrontendPassRequestController@index')->name('anonymous-request-a-pass');
Route::post('anonymous-request-a-pass-submit', 'Frontend\FrontendPassRequestController@store')->name('anonymous-request-a-pass-submit');

Route::resource('two-factor-verification', 'TwoFactorVerification');

Route::get('password-reset', 'Frontend\PasswordController@passwordReset')->name('password-reset');
Route::post('password-reset-save', 'Frontend\PasswordController@passwordResetPost')->name('password-reset-save');

// new addition reset password @mazhar
Route::post('reset-password', 'Admin\UserController@resetPassword');


Route::get('get-contact-in-dnc-by-resident-id/{id}', 'API\UserContactsController@getContactInDncByResidentId2')->name('dnc-by-resident');

//admin routes
Route::group(['middleware' => ['auth:web', 'admin', 'adminDeactivate'], 'prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::post('get-remote-guard-keys', 'Admin\RemoteGuardController@getRemoteGuardKeys')->name('get-remote-guard-keys');


    Route::get('/', 'Admin\DashboardController@index')->name('dashboard')->middleware('checkGuardAdmin');
    Route::get('/dashboard', 'Admin\DashboardController@index')->name('dashboard')->middleware('checkGuardAdmin');

    Route::resource('dashboard-setting', 'Admin\DashboardSettingController')->middleware('checkGuardAdmin');

    Route::resource('connected-pi', 'Admin\ConnectedPiController');
    Route::get('connected-pi-data', 'Admin\ConnectedPiController@connectedPiData')->name('connected-pi-data');
    Route::resource('passes', 'Admin\PassController');
    Route::get('passes-data', 'Admin\PassController@passesData')->name('passes-data');
    Route::post('pass-recipients', 'Admin\PassController@passRecipients')->name('pass-recipients');

    Route::resource('network', 'Admin\NetworkController');
    Route::get('network-data', 'Admin\NetworkController@networkData')->name('network-data');

    Route::resource('remote-guard', 'Admin\RemoteGuardController');
    Route::get('remote-guard-data', 'Admin\RemoteGuardController@remoteGuardData')->name('remote-guard-data');

    Route::group(['middleware' => 'checkKiosk'], function () {

        Route::get('queuejob', function () {
            Artisan::call('queue:work');
        });
        // Profile
        Route::resource('password', 'Admin\PasswordController');
        Route::resource('profile', 'Admin\ProfileController');

        Route::resource('pre-approved', 'Admin\PreApproveController');
        Route::get('pre-approved-data', 'Admin\PreApproveController@preApprovedData')->name('pre-approved-data');

        Route::resource('iono-heartbeat', 'Admin\IonoHeartbeatLogController');
        Route::get('iono-heartbeat-logs-data', 'Admin\IonoHeartbeatLogController@ionoHeartbeatLogsData')->name('iono-heartbeat-logs-data');

        //csv notifications
        Route::post('csv-notifications', 'Admin\DashboardController@csvNotifications')->name('csv-notifications');
        Route::post('csv-notification-viewed', 'Admin\DashboardController@csvNotificationViewed')->name('csv-notification-viewed');

    });

    //users routes
    Route::group(['prefix' => 'user', 'as' => 'user.'], function () {

        //guests routes
        Route::resource('guests', 'Admin\UserController')->middleware(['checkGuardAdmin']);
        Route::get('/banned-guests', 'Admin\UserController@bandGuest')->middleware(['checkGuardAdmin'])->name('banned-guests'); // 'checkCommunityAdmin',

        Route::post('/add-banned-user', 'Admin\UserController@addbandGuest')->middleware(['checkGuardAdmin'])->name('add-banned-user');
        Route::get('/banned-user', 'Admin\UserController@addbandGuestForm')->name('add-banned-user-form');
        Route::get('/guest-data', 'Admin\UserController@guestData')->name('guest-data');
        Route::get('/guest-band-data', 'Admin\UserController@guestBandData')->name('guest-band-data');
        Route::get('/get-community-list', 'Admin\UserController@getCommunity')->middleware(['checkGuardAdmin'])->name('get-community-list');
        Route::post('resend-temporary-password-guest/{id}', 'Admin\UserController@resendTemporaryPassword')->name('resend-temporary-password-guest');
        //revoke resident
        Route::post('revoke-resident', 'Admin\UserController@revokeResident')->name('revoke-resident');
        Route::post('delete-guest/{userId}', 'Admin\UserController@deleteGuest')->name('delete-guest');

        Route::post('check-guest-permission', 'Admin\UserController@checkGuestPermission')->name('check-guest-permission');
        Route::post('check-banned-permission', 'Admin\UserController@checkBannedPermission')->name('check-banned-permission');

        Route::post('assign-banned-permission', 'Admin\UserController@assignBannedPermission')->name('assign-banned-permission');
        Route::post('assign-guest-permission', 'Admin\UserController@assignGuestPermission')->name('assign-guest-permission');
        Route::post('make-resident', 'Admin\UserController@makeResident')->name('make-resident');
        Route::post('get-user', 'Admin\UserController@getUser')->name('get-user');
        Route::post('suspend-guest/{userId}', 'Admin\UserController@suspendGuest')->name('suspend-guest');
        Route::post('unsuspend-guest/{userId}', 'Admin\UserController@unsuspendGuest')->name('unsuspend-guest');

        //community admins routes
        Route::resource('/community-admins', 'Admin\CommunityAdminController')->middleware('checkGuardAdmin');
        Route::get('/community-admins-data', 'Admin\CommunityAdminController@communityAdminsData')->name('community-admins-data');
        Route::post('delete-community-admin/{userId}', 'Admin\CommunityAdminController@deleteCommunityAdmin')->name('delete-community-admin');
        Route::post('deactivate-admin-status', 'Admin\CommunityAdminController@deactivateCommunityAdmin')->name('deactivate-community-admin');
        Route::post('activate-admin-status', 'Admin\CommunityAdminController@activateCommunityAdmin')->name('activate-community-admin');

        Route::group(['middleware' => 'checkKiosk'], function () {

            //Mark:- Kiosk Admin Routes
            Route::resource('/kiosk-admins', 'Admin\KioskAdminController')->middleware('checkGuardAdmin');
            Route::get('/kiosk-admins-data', 'Admin\KioskAdminController@kioskAdminsData')->name('kiosk-admins-data');
            Route::post('delete-kiosk-admin/{userId}', 'Admin\KioskAdminController@deleteKioskAdmin')->name('delete-kiosk-admin');
            Route::post('deactivate-kiosk-status', 'Admin\KioskAdminController@deactivateKioskAdmin')->name('deactivate-kiosk-admin');
            Route::post('activate-kiosk-status', 'Admin\KioskAdminController@activateKioskAdmin')->name('activate-kiosk-admin');

        });

        //security guards routes
        Route::resource('guards', 'Admin\GuardController')->middleware('checkGuardAdmin');
        Route::get('/guards-data', 'Admin\GuardController@guardData')->name('guards-data');

        Route::group(['middleware' => 'checkKiosk'], function () {

            Route::post('/send-reset-link', 'Admin\GuardController@sendResetLink')->name('send-reset-link');
            Route::post('/check-guard-permission', 'Admin\GuardController@checkGuardPermission')->name('check-guard-permission');
            Route::post('/guard-permission', 'Admin\GuardController@guardPermission')->name('guard-permission');
            Route::post('delete-guard/{userId}', 'Admin\GuardController@deleteGuard')->name('delete-guard');
            Route::post('deactivate-guard-status', 'Admin\GuardController@deactivateGuard')->name('deactivate-guard');
            Route::post('activate-guard-status', 'Admin\GuardController@activateGuard')->name('activate-guard');
            //revoke guard
            Route::post('revoke-guard', 'Admin\GuardController@revokeGuard')->name('revoke-guard');
            Route::post('resend-guard-verification-code', 'Admin\GuardController@resendGuardVerificationCode')->name('resend-guard-verification-code');

            Route::group(['prefix' => 'guard-appoint', 'as' => 'guard-appoint.'], function () {
                Route::resource('appoint-locations', 'Admin\GuardAppointLocationController')->middleware('checkGuardAdmin');
                Route::get('guard-appoint-location-data', 'Admin\GuardAppointLocationController@guardAppointLocationData')->name('guard-appoint-location-data');
            });
        });

    });


    //residential prefix

app/Models/AdminPanelNotifications.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class AdminPanelNotifications extends Model
{
    //
}

app/Models/Announcement.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;

class Announcement extends Model
{
    use SoftDeletes;
    protected $guarded = ['id'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
    public function community()
    {
        return $this->belongsTo(Community::class);
    }
}

app/Models/AuthLog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class AuthLog extends Model
{
    use SoftDeletes;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'ip_address', 'user_agent', 'user_id',
    ];

    public function user(){
        return $this->belongsTo(User::class);
    }
}

app/Models/BannedCommunityUser.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class BannedCommunityUser extends Model
{
    use SoftDeletes;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'community_id', 'user_id','phone_number','license_plate','user_name'
    ];

    public function user()
    {
        return $this->belongsTo(User::class,'user_id');
    }

    public function community() {
        return $this->belongsTo(Community::class, 'community_id');
    }

}

app/Models/Camera.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Camera extends Model
{
    use SoftDeletes;
    protected $guarded = ['id'];

    public function community(){
        return $this->belongsTo(Community::class,'community_id');
    }

    public function scanner(){
        return $this->belongsTo(Scanner::class,'scanner_id');
    }

    public function connectedpie(){
        return $this->belongsTo(ConnectedPie::class,'connected_pi_id');
    }
}

app/Models/CameraSocket.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CameraSocket extends Model
{
    //

    protected $fillable = ['mac_address', 'socket_id', 'scan_log_id','remote_guard_id'];
}

app/Models/CameraSocketImage.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CameraSocketImage extends Model
{
    //
    protected $fillable = ['mac_address', 'ImageURL', 'scan_log_id','plateNum'];
    protected $appends = ['fullImageUrl'];

    //get license image url from s3 bucket
    public function getFullImageUrlAttribute()
    {
        return getS3Image($this->ImageURL);
    }





}

app/Models/Community.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Community extends Model
{
    use SoftDeletes;
    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = ['community_image_url'];


    protected $guarded = ['id'];

    public function houses(){
        return $this->hasMany(House::class);
    }

    public function timezone(){
        return $this->belongsTo(Timezone::class);
    }

    //get community image url
    public function getCommunityImageUrlAttribute(){
        if( isset($this->attributes['community_logo']) && !empty($this->attributes['community_logo']) ){
            $filepath =  base_path('public/images/communities/' . $this->attributes["community_logo"]);
            if(file_exists($filepath)){
                return asset('images/communities/'.$this->attributes["community_logo"]);
            }else{
                return asset('images/communities/default-community.png');
            }
        }
        return asset('images/communities/default-community.png');
    }

    public function locations(){
        return $this->hasMany(Location::class);
    }

    public function emailTemplates(){
        return $this->hasMany(EmailTemplate::class);
    }

    public function scanner()
    {
        return $this->hasOne(Scanner::class, 'community_id');
    }

    public function webRelay()
    {
        return $this->hasOne(WebRelay::class, 'community_id');
    }

    public function remoteGuard()
    {
        return $this->hasOne(RemoteGuard::class, 'community_id');
    }

}

app/Models/ConnectedPie.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ConnectedPie extends Model
{
    use SoftDeletes;
    protected $fillable = ['name', 'mac_address', 'dynamic_url', 'uid', 'camera_email', 'camera_password', 'community_id'];

    public function community()
    {
        return $this->belongsTo(Community::class);
    }


}

app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    protected $guarded = ['id'];

    /**
     * get formatted phone number
     * @return string
     */
    public function getFormattedPhoneAttribute()
    {
        $phone = $this->phone_number;
        if (empty($phone)){
            return '';
        }

        if($this->dial_code == "504")
        {
            $a1 = substr($phone, 0, 4);
            $a2 = substr($phone, 4, 4);
            return $a1."-".$a2;
        }
        else if($this->dial_code == "+504")
        {
            $a1 = substr($phone, 0, 4);
            $a2 = substr($phone, 4, 4);
            return $a1."-".$a2;
        }

        $ac = substr($phone, 0, 3);
        $prefix = substr($phone, 3, 3);
        $suffix = substr($phone, 6);
        return "({$ac}) {$prefix}-{$suffix}";
    }

    public function user()
    {
        return $this->belongsTo(User::class,'phone_number','phone_number');
    }
}

app/Models/ContactCollection.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ContactCollection extends Model
{

}

app/Models/ContactGroup.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ContactGroup extends Model
{
    use SoftDeletes;
    protected $guarded = ['id'];

    public function userContacts()
    {
        return $this->belongsToMany(UserContact::class, 'contact_collections')->wherePivotNull('deleted_at');
    }

    public function contactCollections()
    {
        return $this->hasMany(ContactCollection::class, 'contact_group_id');
    }
}

app/Models/Country.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    //
}

app/Models/CountryPhoneFormat.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CountryPhoneFormat extends Model
{
    //
}

app/Models/CsvImport.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CsvImport extends Model
{
    //
    protected $fillable = ['email','type','file_name'];
}

app/Models/Dashboard.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Dashboard extends Model
{
    use SoftDeletes;

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $guarded = ['id'];
}

app/Models/DashboardSetting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class DashboardSetting extends Model
{
    use SoftDeletes;
}

app/Models/DeviceType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class DeviceType extends Model
{
    use SoftDeletes;
    protected $guarded = ['id'];
}

resources/views/frontend/passes/models/pass-detail-model.blade.php
<style>

    .highlight {
        background: #6a87bc;
        color: #fff;
        padding: 10px 10px;
        margin: 8px -15px;
        width: calc(100% + 30px);
    }

    .to-date-1 h4 {
        font-size: 14px;
    }

    .t-d span {
        font-size: 12px;
    }

    .modal-lg-custom {
        max-width: 600px;
    }

    .sender-1 h4 {
        font-size: 16px;
        font-weight: bolder;
    }

    .sender-1 p {
        font-size: 14px;
        margin-bottom: 7px;

    }

    .m-cen {
        margin: 0 auto;
    }

</style>
<div class="modal fade" id="pass-detail-modal">
    <div class="modal-dialog modal-lg-custom">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="pass-event-name">Event </h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form role="form" method="post" action="#"
                  class="ajax-form" id="">
                <div id="printpassdetails" class="modal-body">
                    <div class="row highlight">
                        <div class="col-sm-4 to_date to-date-1">
                            <h4>Starts</h4>
                            <div class="row">
                                <div class="col-sm-8">
                                    <div class="d-flex flex-column t-d">

                                        <span class="dt1 " id="to-date"></span>
                                        <span class="tm1" id="to-date-time"></span>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <i class="fa fa-clock-o" aria-hidden="true"></i>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4 for_date to-date-1">
                            <h4>Expires</h4>
                            <div class="row">
                                <div class="col-sm-8">
                                    <div class="d-flex flex-column t-d">

                                        <span class="dt1" id="for-date">{{--Feb 2 2121--}}</span>
                                        <span class="tm1" id="for-date-time">{{--12:45 PM--}}</span>
                                    </div>

                                </div>
                                <div class="col-sm-3">
                                    <i class="fa fa-clock-o" aria-hidden="true"></i>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4 licence_image">
                            <img src="https://zuulsystem-upgrade.dev/assets/frontend/img/zxc.png"
                                 id="pass-licence-image" style="max-width: 100%">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4 sender sender-1">
                            <h4>Sender Name</h4>
                            <p class="name" id="sender-name"></p>
                        </div>
                        <div class="col-sm-4 sender sender-1">
                            <h4>Community Name</h4>
                            <p class="community" id="sender-community-name"></p>
                            <p class="visitor_type yellow-background" style="background: yellow !important"
                               id="visitor-type"></p>
                        </div>
                        <div class="col-sm-4 sender sender-1">
                            <button class="btn add_to_contact" style="display: none;">
                                Add To Contact
                            </button>
                            <p class="add_to_contact_message"></p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4 sender sender-1">
                            <h4>Sender Phone #</h4>
                            <p class="phone" id="sender-phone-number"></p>
                        </div>
                        <div class="col-sm-4 sender sender-1">
                            <h4>Directions</h4>
                            <p class="description" id="pass-description"></p>
                        </div>
                        <div class="col-sm-4 sender sender-1">
                            <button class="btn m-cen get_directions btn-danger d-flex">
                                Get Directions
                            </button>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4 vehicle sender-1">
                            <h4>Vehicle Detail</h4>
                            <p class="licence_plate" id="vehicle-license-plate"></p>
                            <p class="make" id="vehicle-make"></p>
                            <p class="model" id="vehicle-model"></p>
                        </div>
                        <div class="col-sm-4">
                            <p>Please use the QR code below for scanning and verification</p>
                        </div>
                        <div class="col-sm-4 qrcode">
                            <img src="https://chart.googleapis.com/chart?chs=200x200&amp;cht=qr&amp;chl=248313201517"
                                 id="qr_code_image" style="max-width: 100%">
                        </div>
                    </div>


                    <input type="hidden" name="_token" value="uYDHpxUVjmJUrlcez18KhOvphr7owTUUZ3XD8qmH">
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-danger m-cen col-8" data-dismiss="modal">Close</button>

                </div>
            </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

resources/views/frontend/passes/models/send-pass-model.blade.php
<div class="modal fade" id="send-pass-modal" style="overflow-y: scroll">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Send A Pass</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form role="form" method="post" action="{{route('passes.passes.store')}}"
                  class="ajax-form" enctype="multipart/form-data">
                <input type="hidden" name="redirect" value="{{route('contacts.index')}}">

                <div class="modal-body">

                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="pass_date">Pass Date</label>
                                <input type="datetime-local" name="pass_date" id="pass_date" placeholder="Pass Date"
                                       class="form-control" min="{{date('Y-m-d')}}">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="pass_type">Pass Type</label>
                                <select name="pass_type" class="form-control" id="pass_type">
                                    <option value="one" selected>One Time</option>
                                    <option value="recurring">Recurring</option>
                                    <option value="self">Self</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="visitor_type">Visitor Type</label>
                                <select name="visitor_type" class="form-control" id="visitor_type">
                                    <option value="friends_family">Family / Friend</option>
                                    <option value="vendor_delivery">Vendor / Delivery</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group">
                                <label for="pass_validity">Pass Validity</label>
                                <select name="pass_validity" id="pass_validity" class="form-control">
                                    <option value="3">3 Hours</option>
                                    <option value="6">6 Hours</option>
                                    <option value="12">12 Hours</option>
                                    <option value="24" selected="selected">24 Hours</option>
                                    <option value="48">48 Hours</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4" id="end_date_div">
                            <div class="form-group">
                                <label for="pass_date">End Date</label>
                                <input type="text" name="end_date" id="end_date" placeholder="End Date"
                                       class="form-control" disabled>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="dial_code">Pass Event</label>
                                <select name="event_id" id="event_id" class="form-control">
                                    @foreach($events as $event)
                                        <option value="{{$event->id}}">{{$event->name}}</option>
                                    @endforeach
                                </select>

                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <button class="btn btn-primary" type="button" data-toggle="modal"
                                        data-target="#map-modal">Change
                                </button>
                            </div>
                        </div>
                    </div>
                    {{--description--}}
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <textarea name="description" readonly id="description"
                                          class="form-control pass_address"></textarea>
                                <input type="hidden" name="lat" id="lat" value="">
                                <input type="hidden" name="lng" id="lng" value="">
                            </div>
                        </div>
                    </div>
                    <div class="row" id="contacts_div">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="selected_contacts">Contact</label>
                                <select name="selected_contacts[]" id="selected_contacts" class="form-control" multiple>

                                </select>
                                <input type="hidden" name="selected_contact_message">
                            </div>
                        </div>
                    </div>

                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">
                        <!----> <span>Add </span>
                    </button>
                </div>
            </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>